### PR TITLE
Added conversion from the DOS-style line-endings to the unix-style

### PR DESCRIPTION
**Pull request by wwarlock**

### CODE REVIEW

**Comment by biemond** [comment]
Thanks but I think you can do dos2unix in 1 statement on linux

just do 

```
 dos2unix /startup.sh
```

and it's better to install dos2unix in the dockerfile (you also use it only in the dockerfile), you can add this to this line
https://github.com/biemond/docker-database-puppet/blob/master/Dockerfile#L9

Thanks

**Comment by wwarlock** [comment]
Hmm, that's strange, I've tried "dos2unix /startup.sh" from command line and it doesn't execute, and no any symbols on STDOUT.
So, I decide to convert as in patch.
Ok, I'll try more.

**Comment by biemond** [comment]
strange 

it should work like this ( the default )
dos2unix /startup
or as this
dos2unix -n in.txt out.txt

**Comment by wwarlock** [comment]
It looks like below

``` bash
[root@d20a5b5c27c8 /]# dos2unix /startup.sh
dos2unix: converting file /startup.sh to UNIX format ...
```

I found dos2unix key `-o`, so I can use it.

``` bash
[root@d20a5b5c27c8 /]# dos2unix -o startup.sh
dos2unix: converting file startup.sh to UNIX format ...
```

**Comment by wwarlock** [comment]
Could you please tell me why installing packages through the Dockerfile is better then through Puppet?

**Comment by biemond** [comment]
it is more you use dos2unix in the dockerfile but you install the package from the puppet site.pp , it is a bit hidden and when you remove it there the docker build will crash.
Now it is together in 1 dockerfile

**Comment by wwarlock** [comment]
Yes, I agree

**Pull request closed without merging**
